### ISSUE TITLE
DRT Service Area

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#11]
Are there options/approaches available to implement a DRT service area, wherein only trips beginning and ending within the service area are accepted?

**Comment by jfbischoff** [comment]
Hi, 
that option indeed exists by now. You can set a 
drtServiceAreaShapeFile as value and set the Operational Scheme to operationalScheme=serviceAreaBased.  What this basically does is creating stops on each link of the service area. For people having activities outside the service area, the maxWalkDistance is applied in order to determine whether drt can be used.
We're working on adding an example for this, but somehow this has not happened yet. :)

**Comment by mr-illington** [comment]
Great, I had not reviewed all the possible drt settings from a full output config yet and have now found the appropriate settings there. 

Relatedly, can I we modify settings in the dvrp and multiModalDRT modules directly in the java runner with something like `config.MultiModeDrtConfigGroup().setdrtServiceAreaShapeFile`...? Or do these settings need to be read in through the xml?

**Comment by jfbischoff** [comment]
Yes, that should work like that:
```
MultiModeDrtConfigGroup mmc = MultiModeDrtConfigGroup.get(config);
        for (DrtConfigGroup drtConfigGroup : mmc.getModalElements()){
            drtConfigGroup.setOperationalScheme(DrtConfigGroup.OperationalScheme.stopbased);

        }
```

**Comment by mr-illington** [comment]
This is working excellent. Thanks
