### ISSUE TITLE
Interpreting drt_walk

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#12]
In my current simulation I have successfully established a DRT service area and implemented a `max drt walk` to stop unrealistic trips that do not start/end in the service area. 

However, I still have a very high number of drt_walk trips that seem to be essentially replacing what would otherwise be normal walk trips outside of the drt service area. 

I'm wondering how to interpret these: are these agents who made a request for drt, but that request was rejected because they were outside the service area (by at least max drt walk distance), so they made a walk trip but it is called drt_walk?

This creates a problem for the way my event handling functions as I can't easily separate times when drt_walk was access/egress from a drt trip, and a purely "walk" trip. 

Should I try setting the mode specific constant for drt_walk slightly more negative than normal walk (which it looks to inherit by default), or is there another way to essentially force these pure "walk" trips that are being labeled drt_walk out?

**Comment by jfbischoff** [comment]
Uh, that is a somewhat philosophical question, as DRT is here merely mimicking what public transport in MATSim is doing by assigning a walk leg. 
Modifying the mode constants may be one way of reducing them. I personally tend to interpret them as pure walk in postprocessing, but opinions on this differ.

Currently @vsp-gleich and @kainagel are working on replacing these hard-coded fallback modes by something more configurable. Maybe they can comment a bit :)

**Comment by mr-illington** [comment]
Ok thanks @jfbischoff. I don't mind interpreting them as pure walk in postprocessing, the question would be rather identifying when a drt_walk has been part of an actual drt trip (with vehicle) and not just an all drt_walk trip. 

I guess there is a way using an ant-join on the agent identifiers as I do identify all agents that have made a "full drt" trip (getting in a vehicle), although this a less ideal approach than having agents that ultimately never touched a drt vehicle simply not labelled drt_walk. 

I need to calculate mode split here for model calibration so it will mean doing this on every run in the calibration process. 

Anyway I will give the anti-join a try as an intermediate solution - thoughts from @vsp-gleich and @kainagel are more than welcome. Thanks!

**Comment by vsp-gleich** [comment]
It seems you are not using the latest matsim weekly release (you have "drt_walk" instead of "drt_fallback"), but some other version after the introduction of drt operation mode service area based, right? 
We made significant changes over the last months and still work on that, so I'm not sure which version you are using. I'll try to explain for the most recent version.

> are these agents who made a request for drt, but that request was rejected because they were outside the service area (by at least max drt walk distance), so they made a walk trip but it is called drt_walk?

Yes, almost. The problem unfolds as follows:

1. A mode choice module changes the mode of a trip to drt. Standard matsim mode choice modules don't take into account whether the trip can actually be served (e.g. service area), because they don't know about such things.
2. The new drt trip is routed by the drt routing module. The drt routing module does know about the drt service area, so it returns null instead of a real drt leg, because drt is unavailable. (This is different from having a RequestValidator which rejects drt requests during mobsim. In that case the rejected agents stuck and have no a drt_walk / etc. replacement leg.)
3. We don't want the agent to have an invalid plan or just stuck (because then he is missing in the rest of the simulated day, reducing congestion effects etc., making analysis hard ...). So we implemented some centralized infrastructure which returns some kind of walk leg as a replacement for the unavailable mode (FallbackRoutingModule, prior to having that, this task was done by the individual pt/drt routers). Walk seems the best guess of an universally available alternative mode. However, we set the mode to "drt_fallback" (previously "drt_walk") to tell the router at the next re-route, that this was intended to be a drt trip. For pt this is more obvious: If no pt route could be found, because the agent missed the last bus, he might find a route in a later iteration if TimeAllocationMutator moved his departure time. Furthermore, calling a pt router and obtaining a "walk" trip is somewhat unexpected behaviour which opens a channel for mode shift from pt to walk without necessarily having a way back if mode choice is disabled.

Steps 1-3 take place during the replanning stage. Drt requests are created and processed only later in the mobsim stage. 

We interpret these fallback modes ("drt_fallback/walk" ...) as normal walk legs.
In the current setup all walk legs for access / egress to/from drt (stops) have mode "non_network_walk", the fallback mode is "drt_fallback" and is only used in the above case of drt being unavailable and "drt_walk" is not used any longer.

As you can see these fallback modes ("drt_fallback/walk" ...) are somewhat confusing for analysis, so we are working on replacing them with having a normal leg of mode walk but with an attribute "routingMode" which saves the intended mode "drt". This will hopefully be merged soon into the master.

**Comment by mr-illington** [comment]
Correct I was previously using the 12.0 SNAPSHOT, not from the weekly release repository which I can confirm did have serviceAreaBased operation working.

Am now trying the weekly release repository which is giving the expected ("drt_fallback/walk" ...) behaviour and seems to be performing well although I will have to do more testing to make sure it has not modified any other aspects of my simulation. 

There was already one small change which was strange: I previously ran with a `maxWalkDistance` 20m in order to get as close as possible to full door2door. Before updated to the weekly this worked. After updated to the weekly, I got a ton of

> WARN StopBasedDrtRoutingModule:171 No access stop found, agent will use fallback mode drt_fallback. Agent Id:

warnings and 0 agents took a DRT vehicle. This is with operation service area based. After increasing this to 200m, it worked fine, so not a huge issue on my end but interesting.

**Comment by jfbischoff** [comment]
>warnings and 0 agents took a DRT vehicle. This is with operation service area based. After increasing this to 200m, it worked fine, so not a huge issue on my end but interesting.
Well monitored :-) There was a small modification as to where exactly a stop is located on a link. This will most likely be related to that change.

**Comment by mr-illington** [comment]
This seems to be working fine in terms of my original question - I can now clearly distinguish `drt_fallback `  (I choose to rename them "walk") which do not involve a drt vehicle at all, and `non_network_walk `acting as access and egress for my drt vehicles. 

Do note, however, that this filtering is not present in the `modestats` output, where everything from `drt_fallback `and `drt `are grouped together under drt. 

This creates an issue in using modestats output to calibrate and watch the convergence over time. Or is there some other reason I'm not getting any `drt_fallback `in my modestats output, despite the fact that there are hundreds of `drt_fallback `records? 

![image](https://user-images.githubusercontent.com/17620869/68526938-79a56100-02e1-11ea-80d5-90dd6c207958.png)

I can try and get this manually at least for the final events output, but it's unfortunately quite a bit more work and does not show the convergence over time...

**Comment by mr-illington** [comment]
Anyway, made an method to leverage the drt_customer_stats number of riders per iteration to manually calculate what I could call *drt vehicle trips* and then merge this back into the modestats and adjust accordingly. 

I'm calling this topic closed - thanks again for the feedback!

**Comment by vsp-gleich** [comment]
> Do note, however, that this filtering is not present in the `modestats` output, where everything from `drt_fallback `and `drt `are grouped together under drt.

This is right a feature and not a bug, because we have only one MainModeIdentifier for the whole simulation setup, which shall consider a drt_fallback leg as an attempt to use drt :-/

As we are moving to separate routing mode and transportation engineering analysis "main mode", we are trying to separate those things.
