### ISSUE TITLE
Deepening Understanding of dvrp Assignment Algorythm 

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#15]
Dear maas team, 

I have read about and experimented with the alpha and beta parameters and have a growing understanding of their influence, but still sometimes find myself a little doubtful on how they influence service quality characteristics (max wait, in-veh tt) and specifically how they relate to the rejection rate. This question is a direct followup to #9 

The specific question I am trying to understand is:

 1. Should the rejection rate go down and approach 0 if there is an oversupply of fleet? OR, is this related to the function of the assignment algorithm as discussed in "City-wide shared taxis: A simulation study in Berlin" - that it maximizes workload and occupancy thus creating a limit to performance improvement from fleet size? 

2. What are the most optimal alpha and beta parms to get as close to maximizing service quality as possible with the current assignment algorythm? That is to say, can I (despite the alyorythms preference to put as many people in a vehicle as possible) move towards a situation that when I oversupply the fleet, I actually see the effect of the extra vehicles in better service performance and lowered rejection rates, purely by setting extreme a and b parms?

An aspect of my research question is to determine the necessary cost of a DRST system to achieve an equlivent level of service provided by an existing conventional bus system. The challenge with this is that the level of service is bounded by the alpha and beta parms, so even with a very small DRST service I don't see radically worse service performance in terms of wait and travel times, just a much higher rejection rate. 

Including rejection rate as a necessary third bounding variable to my research question is then a logical approach, but I'm finding in my scenarios that even with large oversupply of vehicles, rejection rates remain very high during the innovation phase. This makes it challenging to answer the question of how much would an equivalent service cost via directly comparing service quality metrics.

**Comment by kainagel** [comment]
What I understood (but maybe I misunderstood) is that you can switch rejection off.  I personally find that a more plausible setting for the replacement of public transit ... since public transit has a service requirement and cannot reject passengers.

Evidently, then, rejection translates into long waiting times.  In principle, then, one would need a behavioral model where passengers that get a long waiting time can decide to use another mode.  And/or allow for pre-booking.  Pre-booking is in the works, but not there yet. 

For the time being, i.e. without prebooking and without the option to switch to a different mode, the remaining option is to make the fleet size large enough so that service quality is acceptable.  

Another parameter is fleet rebalancing: Even if much of the fleet is idle, this is of little help if all vehicles are too far away.

**Comment by mr-illington** [comment]
I would certainly be interested in experimenting with rejections off. I agree this is a plausible comparison to pt (although trying to on pt vehicles at peak hours in some cities arguably comes close to rejection!), and without this I was planning to try and enforce a low rejection of 3-6% which many studies have benchmarked. 

My behavioural model would allow for this, and in fact I expect I will get interesting results as my scenarios are designed to compare the spatial component of DRST via **A)** replacing shuttle bus connections to two satellite locations (only 2 stops on a line, spacing > 8km, therefore alternative modes walk and bike which are available will be a bit unrealistic due to distance) vs. **B)** replacing conventional bus lines (stop density <1km) within a dense cluster (where walk and bike remain more realistic). 

Did I understand correctly that switching rejections off may be a current features? Do you have any additional info on using it? I have to say I have not seen a setting for this yet. I am on the weekly release. 

I have not considered or really spent time on understanding fleet re-balancing yet, but I will give that a look.

**Comment by mr-illington** [comment]
Oh I see now, you must be referring to `<param name="rejectRequestIfMaxWaitOrTravelTimeViolated" value="true" />`. Got it.

**Comment by jfbischoff** [comment]
Hi,
yes, that is the right parameter to chose. Keep in mind that agents, who otherwise would be rejected, will now endure a longer waiting time. However, agents who are already in a vehicle will not be delayed beyond their initial detour tolerance (defined by alpha and beta parameters). 

Vehicle Rebalancing is enabled in the example config scripts provided. Depending on your scenario size, you may want to increase the cell size and time interval. We are currently in the process of publishing a paper on the rebalancing. It should be available on the VSP homepage sometime in December.

**Comment by michalmac** [comment]
One more clarification re `rejectRequestIfMaxWaitOrTravelTimeViolated`: This allows inserting a request despite the max wait time and/or travel time being violated. However, if there is not enough vehicles, and they are already fully planned until their operations end time, new requests will be rejected.

A partial workaround: extend the vehicle operation time: e.g. 60 hours instead of 30 (of course, you can always increase the vehicle capacity or add more vehicles, but then you need to revert these in later iterations).

Vehicle relocation works best for large-scale scenarios. When having only a few buses, but also a limited number of stops (operation scheme is "stopBased"), it could also work fine, and probably best with a customised zonal system (like 1 zone per each stop). If you do not want to implement such, you can try using a very small cell size.
