### ISSUE TITLE
Taxi Contribution: alternative taxi assignment algorithms available?

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#9]
Dear all, 

In it is noted in Bischcoff et al., 2017 (City-wide shared taxi Berlin case study) that "shared taxis are dynamically routed using an insertion heuristic that aims at minimizing the total taxi workload measured as the total time spent on handling requests". 

In Leisch & Bischoff, 2018 (Should SAVs Replace Buses), this taxi assignment algorithm is noted as a limitation on the ability to meaningfully reduce wait and travel times, including with the introduction of larger fleet sizes (e.g. only 250 veh of fleet of 1000 used). 

I'm wondering if there are presently alternative taxi assignment algorithms available that allow for the optimization of different objectives besides minimizing the total taxi workload? For example, I would be interested in the objective function minimize average travel and wait times irregardless of occupancy rates or VKT, allowing to test the tradeoffs between these variables under different fleet structures and demand rates.

**Comment by michalmac** [comment]
Currently, the insertion algorithm is the only one available in the DRT contrib (shared rides) and many available in the taxi contrib (non-shared rides), most of them with a choice of objective.

Regarding the DRT optimisation, there are two possible ways to add more flexibility:
1.  starting from scratch and writing a new `DrtOptimizer`
2. using the existing `DefaultDrtOptimizer` (with the existing fleet rebalancing approach), but with a new `UnplannedRequestInserter` (responsible for making assignments for new incoming passengers)
 3. using the existing `DefaultDrtOptimizer` with the existing `DefaultUnplannedRequestInserter`, but only modifying the cost function that is used when assessing different potential insertion points for each incoming request.

(1) and (2) are require lots of work if you want to have it operational for large fleets (like thousands of vehicles). We have put lots of effort into making it computationally efficient (including parallelisation) and scalable.

(3) Currently there is only one `InsertionCostCalculator` (with a configurable `PenaltyCalculator`), but we can expose an interface so that you can implement your own cost calculator (=cost function).

**Comment by mr-illington** [comment]
My fleet will not reach thousands, perhaps 200 vehicles at most. But it sounds like the third option might be the most straight forward. 

This is great for now, I will get back to you when I am at a further stage in my understanding.

**Comment by mr-illington** [comment]
One more question: are you aware of any published examples where the cost function of the DRT contrib are being modified in a similar way to what I describe (e.g. minimize combination of wait and travel time)?

**Comment by michalmac** [comment]
Not specifically about the DRT contrib. But in general, there are many studies that use some sort of insertion heuristics with different cost functions. I guess many of such functions can be used in the DRT contrib (once the `InsertionCostCalculator` interface is exposed).
